In [2]:
import pandas as pd
from pathlib import Path

LOADING DATA

In [ ]:
# parquet file storage for more compressed representation vs JSON
data_path = Path.cwd() / "raw_overflow_data.parquet"
print(f"Data exist: {data_path.exists()}")
print(f"Check if is a file: {data_path.is_file()}")

Data exist: True
Check if is a file: True

In [4]:
# extracting the data with pandas
df = pd.read_parquet(data_path)
df.head()

,topic,question_title,question_body,answer_body
0,ABSTRACT CLASSES,Interfaces vs Types in TypeScript,What is the difference between these statement...,Update March 2021: The newer TypeScript Handbo...
1,ABSTRACT CLASSES,Can an abstract class have a constructor?,Can an abstract class have a constructor?\n\nI...,"Yes, an abstract class can have a constructor...."
2,ABSTRACT CLASSES,How to determine if a type implements an inter...,Does reflection in C# offer a way to determine...,You have a few choices:\n\ntypeof(IMyInterface...
3,ABSTRACT CLASSES,C# Interfaces. Implicit implementation versus ...,What are the differences in implementing inter...,Implicit is when you define your interface via...
4,ABSTRACT CLASSES,Why can't static methods be abstract in Java?,The question is in Java why can't I define an ...,The abstract annotation to a method indicates ...

In [5]:
print(f"Null values check.")
df.isna().sum()

Null values check.

topic             0
question_title    0
question_body     0
answer_body       0
dtype: int64

In [6]:
# all topics
topics = df['topic'].unique()
topics

<ArrowStringArray>
[            'ABSTRACT CLASSES',                  'AGGREGATION',
                   'ALGORITHMS',                       'ARRAYS',
                 'BINARY TREES',        'C CHARACTER FUNCTIONS',
                  'COMPOSITION',           'DESIGN AND TESTING',
                'ENCAPSULATION',                 'GRAPH THEORY',
                  'HASH TABLES',                  'INHERITANCE',
                  'LINKED LIST',                         'MAPS',
                      'MERGING', 'MINIMAL AND COMPLETE CLASSES',
               'MULTIWAY TREES',                          'OOP',
                   'PARAMETERS',                     'POINTERS',
                       'QUEUES',                      'RECORDS',
                    'SEARCHING',                         'SETS',
                      'SORTING',                       'STACKS',
                      'STRINGS',                        'TREES',
   'TWO DIMENSIONAL STRUCTURES',                      'VECTORS']
Length: 30, dtype: str

In [7]:
# 3000 was the max amount of data pulled per topic, trying to see if there's undersampled classes

def topics_under_size(df, counts=3000):
    
    topic_counts = df.loc[:,'topic'].value_counts()
    topic_counts_filter = topic_counts < counts
    return topic_counts[topic_counts_filter].sort_values()

topics_under_size(df)

topic
MINIMAL AND COMPLETE CLASSES     611
MULTIWAY TREES                   670
COMPOSITION                      695
ENCAPSULATION                    841
GRAPH THEORY                    1319
AGGREGATION                     1477
HASH TABLES                     2119
Name: count, dtype: int64

In [8]:
# we can fix some of these with mapping close topics together.
topic_map = {
    'COMPOSITION' : 'OOP_CONCEPTS',
    'AGGREGATION' : 'OOP_CONCEPTS',
    'ENCAPSULATION' : 'OOP_CONCEPTS',
    'MINIMAL AND COMPLETE CLASSES' : 'OOP_CONCEPTS',
    'GRAPH THEORY' : 'ADVANCED_TREES_GRAPHS',
    'MULTIWAY TREES' : 'ADVANCED_TREES_GRAPHS',
}

# while we can't get all classes to 3k we can get close
# during training, we can class weights to give give classes equal influences during training
mapped_df = df.copy()
mapped_df['topic'] = df['topic'].replace(topic_map)

topics_under_size(mapped_df)

topic
ADVANCED_TREES_GRAPHS    1989
HASH TABLES              2119
Name: count, dtype: int64

VISUALIZING DATA (KINDA)

In [9]:

def random_sample_topics(df, number_per_topic=2):
    
    # finding the count for smallest group
    smallest_topic = df['topic'].value_counts().min()
        
    # randomly sample 
    random_samples = df.groupby('topic').sample(n=number_per_topic, random_state=42)

    return random_samples.drop(columns=['question_title'])
    
random_sample_topics(mapped_df)

,topic,question_body,answer_body
1801,ABSTRACT CLASSES,I'm trying to serialize my data structures in ...,This is a little bit weird but I'm going to an...
1190,ABSTRACT CLASSES,Playground link: http://play.golang.org/p/Ebf5...,"text/template is special casing interface{}, s..."
21949,ADVANCED_TREES_GRAPHS,Given two nodes A and B from a directed JUNG g...,I found a solution myself.\n\nMy problem has t...
21584,ADVANCED_TREES_GRAPHS,The classic travelling salesman problem says y...,You can just replace the distances with the sh...
6173,ALGORITHMS,The binary search is highly efficient for unif...,There's a deep connection between binary searc...
5063,ALGORITHMS,I have some theoretical/practical problem and ...,I am going to try and first formalize the prob...
8909,ARRAYS,Starting with the following code...\n\nbyte fo...,The JLS (§5.2) has special rules for assignmen...
7603,ARRAYS,Will this work for testing whether a value at ...,"Conceptually, arrays in JavaScript contain arr..."
10781,BINARY TREES,I am trying to create a deep copy of my binary...,You're not performing a deep copy of your root...
10660,BINARY TREES,I need a sorted set of objects and am currentl...,"You're defining one criteria to compare, but y..."
15734,C CHARACTER FUNCTIONS,"In my C program, I expected the result of sala...",salary and mobile members of the struct are ar...
13831,C CHARACTER FUNCTIONS,"Specifically, the code sample here works great...",In the spirit of hacking together quick answer...
19012,DESIGN AND TESTING,The Go testing package mentions example functi...,Example functions are usage examples of a pack...
19376,DESIGN AND TESTING,I'm using ngx-toastr with my angular 2 applica...,I think i would require more information for t...
24122,HASH TABLES,"As in the title, I have a hashtable which cont...","You are creating your user interface twice, bu..."
22760,HASH TABLES,My current implementation of an Hash Table is ...,You don't have to modify the hash function for...
26302,INHERITANCE,I have an class which inherit two interfaces:\...,ClientClass::ClientClass()\n{\n auto pMulti...
25391,INHERITANCE,"Regex is on string's only, but what if that fu...","String inheritance\n\nAfter some research, I f..."
28099,LINKED LIST,I have a LinkedList Node class: \n\npublic sta...,Simply said it iterates the linked list and re...
30078,LINKED LIST,I want to make a method in a circular linked l...,Because you use a do while loop the seconden a...
30647,MAPS,I want to insert a key-value pair into dict if...,"You do not need to call d.keys(), so\n\nif key..."
32543,MAPS,I'm looking for a go language capability simil...,The map type. http://golang.org/doc/effective_...
34449,MERGING,I am looking for a solution that will allow me...,Use this.\nhttp://itextpdf.com/\nIt works with...
36326,MERGING,\nI want to merge some rows if they are nearly...,If you measure similarity by occurrence of com...
38154,OOP,I am looking for ways / best practices on test...,"As properly put by lunaryon, it is not possibl..."
37746,OOP,I have recently had two telephone interviews w...,"While your question indicates it's for ""genera..."
3184,OOP_CONCEPTS,Using R version 3.1.3 I'm attempting to count ...,I'm assuming your date/times are in POSIXct fo...
4264,OOP_CONCEPTS,"I have the following route:\n\n&lt;route id=""m...",Look at the code example the page I mentioned;...
40896,PARAMETERS,\nclass C {\n T a;\npublic:\n C(T a): a(a) {...,Yes it is legal and works on all platforms. \n...
42799,PARAMETERS,How would I either create a helper or use the ...,You want to use the request object. Here is a ...
46662,POINTERS,I have a structure like this\n\nstruct node\n{...,C always passes by value. To change a variable...
46199,POINTERS,The following doesnt compile in Intel Fortran ...,Add the nopass attribute to the declaration of...
48808,QUEUES,I am trying to use beanstalk for queuing a lar...,Until 'named jobs' are done and the software r...
48041,QUEUES,I am using Thread::Queue to push an array onto...,"Since you never call $QUEUE-&gt;end(), your th..."
51953,RECORDS,#!/usr/bin/perl -w\nuse strict;\nuse warnings;...,Method calls aren't interpolated in double quo...
52252,RECORDS,I am using FMOD to play some sounds and I woul...,To redirect everything that would go to the sp...
55723,SEARCHING,I want to search and replace case sensitive st...,This is a subject that has interested me for a...
53322,SEARCHING,Is there a function that searches a sequence o...,"You can use ReplaceList with a ""prefix"" and ""s..."
57515,SETS,I am looking for a Pythonic way (the less code...,"I'd use a Counter, which is a kind of defaultd..."
58427,SETS,"I am calculating intersection, union and diffe...",I don't think so.\n\nOne of the pre-condition ...
60389,SORTING,I have a class representing something with a f...,Check out http://wiki.python.org/moin/HowTo/So...
61281,SORTING,I'm trying to write a custom exporter for Blen...,"Change \n\nvertices = sorted(vertices, key = l..."
62303,STACKS,Environment： Xcode 11.3.1/Swift 5\n\nHere is t...,I guess the behavior is because the compiler h...
63280,STACKS,"I have a list of matrices with size of (63,32,...",If I understand correctly what you're trying t...
65411,STRINGS,I discovered this oddity:\n\nfor (long l = 494...,"The number 4946144450195624 fits 64 bits, and ..."
67534,STRINGS,"Just looked at function \n\nstr_pad($input, $p...","You're looking for a string insert, not a padd..."
68448,TREES,\n Possible Duplicate:\n Permutations - all ...,"&lt;?php\n\nfunction pc_permute($items, $perms..."
70418,TREES,Object:\n[\n {\n &quot;Item&quot;:{\n ...,You could use this recursive function. As an e...
72356,TWO DIMENSIONAL STRUCTURES,"I would to create an array with the ""shape"" (n...",Here is a method for the circle in 2D.\n\ndef ...
72007,TWO DIMENSIONAL STRUCTURES,I'm sorry if I didn't pick a descriptive or co...,Try this:\n\n#include &lt;iostream&gt;\nusing ...
74634,VECTORS,When I install vector with:\n\ncabal install v...,You can pass extra options to programs run by ...
75170,VECTORS,class foo {\n public:\n friend ostream&a...,ostream&amp; operator &lt;&lt; (ostream &amp;o...

NOTE: Due to the nature of our data (heavily code-based), common cleaning techniques can serve more to hinder than help. According to the average sample, there are a lot of new lines. These are likely the things that need the most attention.

In [10]:
import html

cleaned_df = mapped_df.copy()

# decode html code back into regular characters
cleaned_df = cleaned_df.apply(html.unescape)

# if the string pattern matches newline or carriage return (\r) ONE or MORE time, replace with space
cleaned_df = cleaned_df.replace(r'[\n\r]+', ' ', regex=True)

In [11]:
random_sample_topics(cleaned_df)

,topic,question_body,answer_body
1801,ABSTRACT CLASSES,I'm trying to serialize my data structures in ...,This is a little bit weird but I'm going to an...
1190,ABSTRACT CLASSES,Playground link: http://play.golang.org/p/Ebf5...,"text/template is special casing interface{}, s..."
21949,ADVANCED_TREES_GRAPHS,Given two nodes A and B from a directed JUNG g...,I found a solution myself. My problem has the ...
21584,ADVANCED_TREES_GRAPHS,The classic travelling salesman problem says y...,You can just replace the distances with the sh...
6173,ALGORITHMS,The binary search is highly efficient for unif...,There's a deep connection between binary searc...
5063,ALGORITHMS,I have some theoretical/practical problem and ...,I am going to try and first formalize the prob...
8909,ARRAYS,Starting with the following code... byte foo =...,The JLS (§5.2) has special rules for assignmen...
7603,ARRAYS,Will this work for testing whether a value at ...,"Conceptually, arrays in JavaScript contain arr..."
10781,BINARY TREES,I am trying to create a deep copy of my binary...,You're not performing a deep copy of your root...
10660,BINARY TREES,I need a sorted set of objects and am currentl...,"You're defining one criteria to compare, but y..."
15734,C CHARACTER FUNCTIONS,"In my C program, I expected the result of sala...",salary and mobile members of the struct are ar...
13831,C CHARACTER FUNCTIONS,"Specifically, the code sample here works great...",In the spirit of hacking together quick answer...
19012,DESIGN AND TESTING,The Go testing package mentions example functi...,Example functions are usage examples of a pack...
19376,DESIGN AND TESTING,I'm using ngx-toastr with my angular 2 applica...,I think i would require more information for t...
24122,HASH TABLES,"As in the title, I have a hashtable which cont...","You are creating your user interface twice, bu..."
22760,HASH TABLES,My current implementation of an Hash Table is ...,You don't have to modify the hash function for...
26302,INHERITANCE,I have an class which inherit two interfaces: ...,ClientClass::ClientClass() { auto pMulti =...
25391,INHERITANCE,"Regex is on string's only, but what if that fu...","String inheritance After some research, I foun..."
28099,LINKED LIST,I have a LinkedList Node class: public static...,Simply said it iterates the linked list and re...
30078,LINKED LIST,I want to make a method in a circular linked l...,Because you use a do while loop the seconden a...
30647,MAPS,I want to insert a key-value pair into dict if...,"You do not need to call d.keys(), so if key no..."
32543,MAPS,I'm looking for a go language capability simil...,The map type. http://golang.org/doc/effective_...
34449,MERGING,I am looking for a solution that will allow me...,Use this. http://itextpdf.com/ It works with b...
36326,MERGING,I want to merge some rows if they are nearly ...,If you measure similarity by occurrence of com...
38154,OOP,I am looking for ways / best practices on test...,"As properly put by lunaryon, it is not possibl..."
37746,OOP,I have recently had two telephone interviews w...,"While your question indicates it's for ""genera..."
3184,OOP_CONCEPTS,Using R version 3.1.3 I'm attempting to count ...,I'm assuming your date/times are in POSIXct fo...
4264,OOP_CONCEPTS,"I have the following route: &lt;route id=""my-a...",Look at the code example the page I mentioned;...
40896,PARAMETERS,class C { T a; public: C(T a): a(a) {;} }...,Yes it is legal and works on all platforms. I...
42799,PARAMETERS,How would I either create a helper or use the ...,You want to use the request object. Here is a ...
46662,POINTERS,I have a structure like this struct node { ...,C always passes by value. To change a variable...
46199,POINTERS,The following doesnt compile in Intel Fortran ...,Add the nopass attribute to the declaration of...
48808,QUEUES,I am trying to use beanstalk for queuing a lar...,Until 'named jobs' are done and the software r...
48041,QUEUES,I am using Thread::Queue to push an array onto...,"Since you never call $QUEUE-&gt;end(), your th..."
51953,RECORDS,#!/usr/bin/perl -w use strict; use warnings; u...,Method calls aren't interpolated in double quo...
52252,RECORDS,I am using FMOD to play some sounds and I woul...,To redirect everything that would go to the sp...
55723,SEARCHING,I want to search and replace case sensitive st...,This is a subject that has interested me for a...
53322,SEARCHING,Is there a function that searches a sequence o...,"You can use ReplaceList with a ""prefix"" and ""s..."
57515,SETS,I am looking for a Pythonic way (the less code...,"I'd use a Counter, which is a kind of defaultd..."
58427,SETS,"I am calculating intersection, union and diffe...",I don't think so. One of the pre-condition of ...
60389,SORTING,I have a class representing something with a f...,Check out http://wiki.python.org/moin/HowTo/So...
61281,SORTING,I'm trying to write a custom exporter for Blen...,"Change vertices = sorted(vertices, key = lamb..."
62303,STACKS,Environment： Xcode 11.3.1/Swift 5 Here is the ...,I guess the behavior is because the compiler h...
63280,STACKS,"I have a list of matrices with size of (63,32,...",If I understand correctly what you're trying t...
65411,STRINGS,I discovered this oddity: for (long l = 494614...,"The number 4946144450195624 fits 64 bits, and ..."
67534,STRINGS,"Just looked at function str_pad($input, $pad_...","You're looking for a string insert, not a padd..."
68448,TREES,Possible Duplicate: Permutations - all po...,"&lt;?php function pc_permute($items, $perms = ..."
70418,TREES,Object: [ { &quot;Item&quot;:{ ...,You could use this recursive function. As an e...
72356,TWO DIMENSIONAL STRUCTURES,"I would to create an array with the ""shape"" (n...",Here is a method for the circle in 2D. def Cre...
72007,TWO DIMENSIONAL STRUCTURES,I'm sorry if I didn't pick a descriptive or co...,Try this: #include &lt;iostream&gt; using name...
74634,VECTORS,When I install vector with: cabal install vect...,You can pass extra options to programs run by ...
75170,VECTORS,class foo { public: friend ostream&amp...,ostream&amp; operator &lt;&lt; (ostream &amp;o...

In [12]:
topic_label_map = {key : value for value, key in enumerate(cleaned_df['topic'].value_counts().index)}
topic_label_map

{'OOP_CONCEPTS': 0,
 'ABSTRACT CLASSES': 1,
 'ALGORITHMS': 2,
 'ARRAYS': 3,
 'BINARY TREES': 4,
 'C CHARACTER FUNCTIONS': 5,
 'DESIGN AND TESTING': 6,
 'INHERITANCE': 7,
 'LINKED LIST': 8,
 'MAPS': 9,
 'MERGING': 10,
 'OOP': 11,
 'PARAMETERS': 12,
 'POINTERS': 13,
 'QUEUES': 14,
 'RECORDS': 15,
 'SEARCHING': 16,
 'SETS': 17,
 'SORTING': 18,
 'STACKS': 19,
 'STRINGS': 20,
 'TREES': 21,
 'TWO DIMENSIONAL STRUCTURES': 22,
 'VECTORS': 23,
 'HASH TABLES': 24,
 'ADVANCED_TREES_GRAPHS': 25}

In [13]:
# label mapping for ML work
cleaned_df['label'] = cleaned_df['topic'].map(topic_label_map)

# seeing the labels worked as intended (all true means nothing was mislabled)
cleaned_df['topic'].value_counts().values == cleaned_df['label'].value_counts().values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [23]:
# saving to parquet
save_path = Path.cwd() / "train_ready.parquet"
cleaned_df.to_parquet(path=save_path)

if save_path.is_file():
    
    try:
        test = pd.read_parquet(save_path)
        
        print('If all zero, then file integrity is good.')
        print((test != cleaned_df).sum())
        
        print(f'Successfully saved: {save_path}')
        
    except Exception as e:
        print('Save Failed.', {e})
else:
    print('Save failed.')

If all zero, then file integrity is good.
topic             0
question_title    0
question_body     0
answer_body       0
label             0
dtype: int64
Successfully saved: c:\All University Materials\Project\ICT304-project\ai\ai_tools\data_preprocessing\train_ready.parquet