In [19]:
import pandas as pd
from pathlib import Path
import json

LOADING DATA

In [20]:
# checking if the dat exists
data_path = Path.cwd() / "SO_queries.json"
print(f"Data exist: {data_path.exists()}")
print(f"Check if is a file: {data_path.is_file()}")

Data exist: True
Check if is a file: True

In [21]:
# extracting the SO queries

with open(data_path, 'r') as file:
    data = []
    for line in file:
        data.append(json.loads(line))
    
df = pd.DataFrame(data)
df = df.drop(columns=['question_title', 'answer_body'])
df.head()

,topic,question_body
0,ABSTRACT_CLASSES_AND_INTERFACES,How do I setup a class that represents an inte...
1,ABSTRACT_CLASSES_AND_INTERFACES,Please explain in an easy to understand langua...
2,ABSTRACT_CLASSES_AND_INTERFACES,Can an abstract class have a constructor?\n\nI...
3,ABSTRACT_CLASSES_AND_INTERFACES,The question is in Java why can't I define an ...
4,ABSTRACT_CLASSES_AND_INTERFACES,(1) List&lt;?&gt; myList = new ArrayList&lt;?&...

In [22]:
print(f"Null values check.")
df.isna().sum()

Null values check.

topic            0
question_body    0
dtype: int64

In [23]:
# all topics
topics = df['topic'].unique()
topics

<ArrowStringArray>
[           'ABSTRACT_CLASSES_AND_INTERFACES',
                                 'ALGORITHMS',
                         'ALGORITHM_ANALYSIS',
                                  'ARRAYS_1D',
                                  'ARRAYS_2D',
                                  'AVL_TREES',
                        'BINARY_SEARCH_TREES',
                        'CLASSES_AND_OBJECTS',
                           'CODING_STANDARDS',
                'COMPOSITION_AND_AGGREGATION',
                               'CONTROL_FLOW',
                            'DESIGN_PATTERNS',
                              'DOCUMENTATION',
                             'DYNAMIC_MEMORY',
                              'ENCAPSULATION',
                         'EXCEPTION_HANDLING',
                                    'FILE_IO',
                   'FUNCTIONS_AND_MODULARITY',
                                     'GRAPHS',
                                'HASH_TABLES',
                                'INHERITANCE',
                                'LINKED_LIST',
                              'MAPS_AND_SETS',
                             'MULTIWAY_TREES',
                                   'POINTERS',
                               'POLYMORPHISM',
                                     'QUEUES',
                                  'SEARCHING',
 'SEPARATION_OF_INTERFACE_AND_IMPLEMENTATION',
                           'SOLID_PRINCIPLES',
                                    'SORTING',
                                     'STACKS',
                                    'STRINGS',
                     'TEMPLATES_AND_GENERICS',
                      'TESTING_AND_DEBUGGING',
                     'UML_AND_CLASS_DIAGRAMS',
                        'VARIABLES_AND_TYPES',
                 'VECTORS_AND_DYNAMIC_ARRAYS']
Length: 38, dtype: str

In [24]:
# 3000 was the max amount of data pulled per topic, trying to see if there's undersampled classes

def topics_under_size(df, counts=1000):
    
    topic_counts = df.loc[:,'topic'].value_counts()
    topic_counts_filter = topic_counts < counts
    return topic_counts[topic_counts_filter].sort_values()

topics_under_size(df)

topic
SOLID_PRINCIPLES                74
AVL_TREES                      117
MULTIWAY_TREES                 186
COMPOSITION_AND_AGGREGATION    291
UML_AND_CLASS_DIAGRAMS         430
ENCAPSULATION                  459
Name: count, dtype: int64

In [25]:
# getting the minory class labels
df_dicts = {}
for column in topics_under_size(df).index:
   df_dicts[column] = df[df['topic'] == column]
   
df_dicts

{'SOLID_PRINCIPLES':                   topic                                      question_body
 26053  SOLID_PRINCIPLES  \n  From Wikipedia :\n  \n  The idea was that ...
 26054  SOLID_PRINCIPLES  The open-closed principle states that "Softwar...
 26055  SOLID_PRINCIPLES  As SOLID principles say, it's better to remove...
 26056  SOLID_PRINCIPLES  I know SOLID principles were written for objec...
 26057  SOLID_PRINCIPLES  I'm currently thinking of "How to design an OS...
 ...                 ...                                                ...
 26122  SOLID_PRINCIPLES  I'm trying to test this custom model where if ...
 26123  SOLID_PRINCIPLES  I would like to see/learn how solid principles...
 26124  SOLID_PRINCIPLES  Keeping things tidy and simple, here is my ini...
 26125  SOLID_PRINCIPLES  In the below example Enums do the amount of pr...
 26126  SOLID_PRINCIPLES  I'm working on my own model of repositories an...

 [74 rows x 2 columns],
 'AVL_TREES':           topic                                      question_body
 5000  AVL_TREES  Assume that I have two AVL trees and that each...
 5001  AVL_TREES  Is the computational complexity of TreeSet met...
 5002  AVL_TREES  I'm having the hardest time trying to figure o...
 5003  AVL_TREES  The third paragraph of wikipedia's article on ...
 5004  AVL_TREES  I know the formula of finding minimum number o...
 ...         ...                                                ...
 5112  AVL_TREES  I want to understand implementation of red bla...
 5113  AVL_TREES  I am implementing the ALV tree, and I need to ...
 5114  AVL_TREES  i tried this function \n\nprivate int height(A...
 5115  AVL_TREES  I'm trying to implement iterator on AVL tree, ...
 5116  AVL_TREES  Adding an element to the AVL tree. Tree curren...

 [117 rows x 2 columns],
 'MULTIWAY_TREES':                 topic                                      question_body
 20867  MULTIWAY_TREES  I have a Java program that stores a lot of map...
 20868  MULTIWAY_TREES  Is there any speed- and cache-efficient implem...
 20869  MULTIWAY_TREES  \n  Possible Duplicate:\n  Where do I find a s...
 20870  MULTIWAY_TREES  UPDATE 3\n\nDone. Below is the code that final...
 20871  MULTIWAY_TREES  Is there any library or documentation/link whi...
 ...               ...                                                ...
 21048  MULTIWAY_TREES  I have the following task:\n\nA word "Superhig...
 21049  MULTIWAY_TREES  class node {\n\n     public:\n     node(){\n  ...
 21050  MULTIWAY_TREES  I'm getting problem with segmentation fault wh...
 21051  MULTIWAY_TREES  Hi I'm using a Trie implementation to solve th...
 21052  MULTIWAY_TREES  I was trying to solve No Prefix Set problem on...

 [186 rows x 2 columns],
 'COMPOSITION_AND_AGGREGATION':                             topic  \
 8117  COMPOSITION_AND_AGGREGATION
 8118  COMPOSITION_AND_AGGREGATION
 8119  COMPOSITION_AND_AGGREGATION
 8120  COMPOSITION_AND_AGGREGATION
 8121  COMPOSITION_AND_AGGREGATION
 ...                           ...
 8403  COMPOSITION_AND_AGGREGATION
 8404  COMPOSITION_AND_AGGREGATION
 8405  COMPOSITION_AND_AGGREGATION
 8406  COMPOSITION_AND_AGGREGATION
 8407  COMPOSITION_AND_AGGREGATION

                                           question_body
 8117  I'm aware of the conceptual differences betwee...
 8118  I am facing a continuing problem distinguishin...
 8119  I know that the compiler sometimes provides a ...
 8120  Can I call constructor of a member in my Class...
 8121  I'm beginning to study OOAD and I'm having dif...
 ...                                                 ...
 8403  \n  Define two classes, Patient and Billing, w...
 8404  I have a problem in composition in Java. I wan...
 8405  I am in the middle of getting my feet wet with...
 8406  so I'm trying to implement an aggregation rela...
 8407  below is my code:\n\nclass Pulley{\nprivate:\n...

 [291 rows x 2 columns],
 'UML_AND_CLASS_DIAGRAMS':                         topic  \
 31127  UML_AND_CLASS_DIAGRAMS
 31128  UML_AND_CLASS_DIAGRAMS
 31129  UML_AND_CLASS_DIAGRAMS
 31130  UML_AND_CLASS_DIAGRAMS
 31131  UML_AND_CLASS_DIAGRAMS
 ...                       ...
 31552  UML_AND_CLASS_DIAGRAMS
 31553  UML_AND_CLASS_DIAGRAMS
 31554  UML_AND_CLASS_DIAGRAMS
 31555  UML_AND_CLASS_DIAGRAMS
 31556  UML_AND_CLASS_DIAGRAMS

                                            question_body
 31127  Is there a good tool that can help to reverse ...
 31128  How do I get IntelliJ 10.5 (on the Mac) to gen...
 31129  Is there a tool that can parse C++ files withi...
 31130  I have been searching for some material that d...
 31131  What is a good Eclipse plugin for generating a...
 ...                                                  ...
 31552  I have this code: \n\n#include &lt;iostream&gt...
 31553  \nI have this UML class diagram, but I don't k...
 31554  \n\nI need to know how to do the relationship ...
 31555  How to show this class in a UML diagram?\n\n  ...
 31556  i have to conceive the following model:\n\ni'v...

 [430 rows x 2 columns],
 'ENCAPSULATION':                topic                                      question_body
 12408  ENCAPSULATION  What is the difference between public, private...
 12409  ENCAPSULATION  I have been reading through the C++ FAQ and wa...
 12410  ENCAPSULATION  Suppose I have a method that returns a read-on...
 12411  ENCAPSULATION  I had an interview today. I had a question fro...
 12412  ENCAPSULATION  I have a project in which we often use Integer...
 ...              ...                                                ...
 12862  ENCAPSULATION  I've declared a private variable in one class ...
 12863  ENCAPSULATION  I have created the following Java program. Its...
 12864  ENCAPSULATION  I have a class Rules() that have a static publ...
 12865  ENCAPSULATION  I tried to decode a published application from...
 12866  ENCAPSULATION  When I became C# lover, I was little disappoin...

 [459 rows x 2 columns]}

In [26]:
sample = df.sample(n=1)
sample.to_dict('records')[0]

new_df = df.copy()
pd.concat([new_df, pd.DataFrame([sample.to_dict('records')[0]])])

,topic,question_body
0,ABSTRACT_CLASSES_AND_INTERFACES,How do I setup a class that represents an inte...
1,ABSTRACT_CLASSES_AND_INTERFACES,Please explain in an easy to understand langua...
2,ABSTRACT_CLASSES_AND_INTERFACES,Can an abstract class have a constructor?\n\nI...
3,ABSTRACT_CLASSES_AND_INTERFACES,The question is in Java why can't I define an ...
4,ABSTRACT_CLASSES_AND_INTERFACES,(1) List&lt;?&gt; myList = new ArrayList&lt;?&...
...,...,...
33553,VECTORS_AND_DYNAMIC_ARRAYS,I have a class called ChessBoard and one of th...
33554,VECTORS_AND_DYNAMIC_ARRAYS,I was looking at the source code for gcc (out ...
33555,VECTORS_AND_DYNAMIC_ARRAYS,I am debugging some C++ code and I have a real...
33556,VECTORS_AND_DYNAMIC_ARRAYS,I know the Vector class is thread-safe for add...
0,HASH_TABLES,"I have a file (more specifically, a log4j conf..."

In [27]:
import ollama

def generate_synth_data(df_examples : pd.DataFrame = None, topic_name= None, batch_gen=50, amount=500, model = 'gemma4:31b-cloud'):
    """
    Generates synthetic data for minority classes.
    """
    count = 0
    with open(Path.cwd() / f'{topic_name}.ndjson', 'a') as j:
        
        while count < amount:
            
            print(f'GENERATING "{topic_name}" samples... progress: {count} / {amount}')
        
            try:
                
                sample = df_examples.sample(n=5).to_dict('records')[0]
                
                response = ollama.chat(model=model,
                            messages=[{'role': 'system', 'content' : f'You are tasked with generating synthetic data in this exact format {{"topic": ..., "question_body" : ...}}. The user will provide examples and from that, you will generate an entirely new question_body under the SAME TOPIC. Everything should be natural sounding. Avoid adding backslashes to keys \\"topics\\" or \\"question_body"\\ is wrong. Use "" around the keys. Generate {batch_gen} copies separated by <SPLT>. Do not add whitespaces or new lines inside the keys.'},
                                    {'role': 'user', 'content' : f'{sample}'}],
                            think=False,
                            options={'temperature' : 0.8})
                
                content = response.message.content
                
                for line in content.split('<SPLT>'):
                    row = json.loads(line.strip())
                    j.write(json.dumps(row) + '\n')
                    j.flush()
                    
                count += batch_gen
            
            except Exception as e:
                print(f'Failed: {e}. Trying again...')

In [28]:
# generating synthetic data to rebalance values
"""
for topic, topic_df in df_dicts.items():
amount = 1000 - len(topic_df)
generate_synth_data(topic_df, topic, batch_gen=50, amount=amount)
"""

'\nfor topic, topic_df in df_dicts.items():\namount = 1000 - len(topic_df)\ngenerate_synth_data(topic_df, topic, batch_gen=50, amount=amount)\n'

In [29]:
df.shape

(33557, 2)

In [36]:
# we can fix some of these with mapping close topics together.
new_df = df.copy()
for topic, topic_df in df_dicts.items():
    
    json_df = pd.read_json(Path.cwd() / f'{topic}.ndjson', lines=1)
    new_df = pd.concat([json_df, new_df])
    
    
new_df.shape

(39064, 2)

In [42]:
new_df['topic'].value_counts()

topic
AVL_TREES                                     1286
COMPOSITION_AND_AGGREGATION                   1268
MULTIWAY_TREES                                1173
UML_AND_CLASS_DIAGRAMS                        1144
SOLID_PRINCIPLES                              1111
ENCAPSULATION                                 1082
ABSTRACT_CLASSES_AND_INTERFACES               1000
ALGORITHMS                                    1000
ALGORITHM_ANALYSIS                            1000
ARRAYS_1D                                     1000
ARRAYS_2D                                     1000
BINARY_SEARCH_TREES                           1000
CLASSES_AND_OBJECTS                           1000
CODING_STANDARDS                              1000
CONTROL_FLOW                                  1000
DESIGN_PATTERNS                               1000
DOCUMENTATION                                 1000
DYNAMIC_MEMORY                                1000
EXCEPTION_HANDLING                            1000
FILE_IO                                       1000
FUNCTIONS_AND_MODULARITY                      1000
GRAPHS                                        1000
HASH_TABLES                                   1000
INHERITANCE                                   1000
LINKED_LIST                                   1000
MAPS_AND_SETS                                 1000
POINTERS                                      1000
POLYMORPHISM                                  1000
QUEUES                                        1000
SEARCHING                                     1000
SEPARATION_OF_INTERFACE_AND_IMPLEMENTATION    1000
SORTING                                       1000
STACKS                                        1000
STRINGS                                       1000
TEMPLATES_AND_GENERICS                        1000
TESTING_AND_DEBUGGING                         1000
VARIABLES_AND_TYPES                           1000
VECTORS_AND_DYNAMIC_ARRAYS                    1000
Name: count, dtype: int64

In [44]:
# checking the number of samples per class
topics_under_size(new_df)

Series([], Name: count, dtype: int64)

VISUALIZING DATA (KINDA)

In [46]:

def random_sample_topics(df, number_per_topic=2):
        
    # randomly sample 
    random_samples = df.groupby('topic').sample(n=number_per_topic, random_state=42)

    return random_samples
    
random_sample_topics(new_df)

,topic,question_body
521,ABSTRACT_CLASSES_AND_INTERFACES,I just encountered a behavior I first thought ...
737,ABSTRACT_CLASSES_AND_INTERFACES,I have an interface class similar to:\n\nclass...
1093,ALGORITHMS,I have three points on the circumference of a ...
1692,ALGORITHMS,I'm trying to efficiently list numbers between...
2612,ALGORITHM_ANALYSIS,I was going through some practice problems and...
...,...,...
489,UML_AND_CLASS_DIAGRAMS,I'm struggling to decide between using a visua...
32212,VARIABLES_AND_TYPES,"So I just started learning Java, its literally..."
31958,VARIABLES_AND_TYPES,Hi I'm new to Java and I have following questi...
33411,VECTORS_AND_DYNAMIC_ARRAYS,im trying to get a vector of integers by using...
32755,VECTORS_AND_DYNAMIC_ARRAYS,I made a vector of constant size to store nega...

NOTE: Due to the nature of our data (heavily code-based), common cleaning techniques can serve more to hinder than help. According to the average sample, there are a lot of new lines. These are likely the things that need the most attention.

In [52]:
import html

cleaned_df = new_df.copy()

# decode html code back into regular characters
cleaned_df = cleaned_df.apply(html.unescape)

# if the string pattern matches newline or carriage return (\r) ONE or MORE time, replace with space
cleaned_df = cleaned_df.replace(r'[\n\r]+', ' ', regex=True)

In [53]:
random_sample_topics(cleaned_df)

,topic,question_body
521,ABSTRACT_CLASSES_AND_INTERFACES,I just encountered a behavior I first thought ...
737,ABSTRACT_CLASSES_AND_INTERFACES,I have an interface class similar to: class II...
1093,ALGORITHMS,I have three points on the circumference of a ...
1692,ALGORITHMS,I'm trying to efficiently list numbers between...
2612,ALGORITHM_ANALYSIS,I was going through some practice problems and...
...,...,...
489,UML_AND_CLASS_DIAGRAMS,I'm struggling to decide between using a visua...
32212,VARIABLES_AND_TYPES,"So I just started learning Java, its literally..."
31958,VARIABLES_AND_TYPES,Hi I'm new to Java and I have following questi...
33411,VECTORS_AND_DYNAMIC_ARRAYS,im trying to get a vector of integers by using...
32755,VECTORS_AND_DYNAMIC_ARRAYS,I made a vector of constant size to store nega...

In [55]:
# cleaned df relable

cleaned_df.columns = {'label' : 'topic', 'content' : 'question_body'}
cleaned_df

,label,content
0,ENCAPSULATION,I am trying to implement a plugin system where...
1,ENCAPSULATION,Suppose I have a class hierarchy where 'Shape'...
2,ENCAPSULATION,I'm working with a library that uses a base cl...
3,ENCAPSULATION,"In C++, if I have a base class pointer pointin..."
4,ENCAPSULATION,I have a base class 'Entity' and derived class...
...,...,...
33552,VECTORS_AND_DYNAMIC_ARRAYS,Looks like a stupid question. But comment to m...
33553,VECTORS_AND_DYNAMIC_ARRAYS,I have a class called ChessBoard and one of th...
33554,VECTORS_AND_DYNAMIC_ARRAYS,I was looking at the source code for gcc (out ...
33555,VECTORS_AND_DYNAMIC_ARRAYS,I am debugging some C++ code and I have a real...
33556,VECTORS_AND_DYNAMIC_ARRAYS,I know the Vector class is thread-safe for add...

In [56]:
# saving to parquet
save_path = Path.cwd() / "train_ready.parquet"
cleaned_df.to_parquet(path=save_path)

if save_path.is_file():
    
    try:
        test = pd.read_parquet(save_path)
        
        print('If all zero, then file integrity is good.')
        print((test != cleaned_df).sum())
        
        print(f'Successfully saved: {save_path}')
        
    except Exception as e:
        print('Save Failed.', {e})
else:
    print('Save failed.')

If all zero, then file integrity is good.
label      0
content    0
dtype: int64
Successfully saved: c:\All University Materials\Project\ICT304-project\ai\ai_tools\data_preprocessing\train_ready.parquet