In [34]:
import pandas as pd

In [35]:
path = r"C:\All University Materials\Project\ICT304-project\ai\ai_tools\data_preprocessing\DATA_BIG.json"
df = pd.read_json(path, lines=True)

df.columns

Index(['topic', 'question_title', 'question_body', 'answer_body'], dtype='str')

In [36]:
df = df.drop(columns=['topic', 'question_title'])
df = df.rename(columns={'question_body' : 'Question', 'answer_body' : 'Answer'})
df

,Question,Answer
0,What is the difference between these statement...,Update March 2021: The newer TypeScript Handbo...
1,Can an abstract class have a constructor?\n\nI...,"Yes, an abstract class can have a constructor...."
2,Does reflection in C# offer a way to determine...,You have a few choices:\n\ntypeof(IMyInterface...
3,What are the differences in implementing inter...,Implicit is when you define your interface via...
4,The question is in Java why can't I define an ...,The abstract annotation to a method indicates ...
...,...,...
76727,I have a problem of how python evaluates vecto...,curve_fit expects a func that returns 1D array...
76728,I have the following dataset:\n\nwow &lt;- dat...,We could remove the values that are min and ma...
76729,I was wondering if it was faster to have a std...,"The vector&lt;MyPoint&gt; is preferable, becau..."
76730,I have a vector of vectors that store pointers...,If you're comparing the pointers themselves th...
76731,I want to store classes derived of a class tem...,What I understand from your question: \n\n\nY...

In [37]:
import html
import re

def clean_for_ai(text):
    
    if not isinstance(text, str):
        return ""

    # 1. Unescape HTML entities (&lt; becomes <, &amp; becomes &, etc.)
    text = html.unescape(text)

    # 2. Normalize newlines
    # Replace 3 or more consecutive newlines with exactly 2 (to maintain paragraph separation)
    text = re.sub(r'\n{3,}', '\n\n', text)

    # 3. Strip leading and trailing whitespace
    text = text.strip()

    return text

df['Question'] = df['Question'].apply(clean_for_ai)
df['Answer'] = df['Answer'].apply(clean_for_ai)
df

,Question,Answer
0,What is the difference between these statement...,Update March 2021: The newer TypeScript Handbo...
1,Can an abstract class have a constructor?\n\nI...,"Yes, an abstract class can have a constructor...."
2,Does reflection in C# offer a way to determine...,You have a few choices:\n\ntypeof(IMyInterface...
3,What are the differences in implementing inter...,Implicit is when you define your interface via...
4,The question is in Java why can't I define an ...,The abstract annotation to a method indicates ...
...,...,...
76727,I have a problem of how python evaluates vecto...,curve_fit expects a func that returns 1D array...
76728,I have the following dataset:\n\nwow <- data.f...,We could remove the values that are min and ma...
76729,I was wondering if it was faster to have a std...,"The vector<MyPoint> is preferable, because MyP..."
76730,I have a vector of vectors that store pointers...,If you're comparing the pointers themselves th...
76731,I want to store classes derived of a class tem...,What I understand from your question: \n\nYou...

In [38]:
df.to_json('stack_overflow_qna_sample.json',orient='records', lines=True)